export const maleFirstNames = [
  "Aarón",
  "Alexander",
  "Alfonso",
  "Ángel Daniel",
  "Antônio",
  "Arturo",
  "Breno",
  "Caio",
  "Cauã",
  "César",
  "Claudio",
  "Danilo",
  "Davi Lucca",
  "Emilio",
  "Enrique",
  "Enzo",
  "Fabrício",
  "Félix",
  "Fernando",
  "Gerardo",
  "Gregorio",
  "Gustavo",
  "Henrique",
  "Homero",
  "Hugo",
  "Iker",
  "Isaac",
  "Israel",
  "Jacobo",
  "Jaime",
  "Javier",
  "Jerónimo",
  "Jesús",
  "Jorge",
  "José",
  "Juan",
  "Julio César",
  "Leonardo",
  "Lorenzo",
  "Luis Fernando",
  "Marcelo",
  "Marcos",
  "Mario",
  "Martín",
  "Matheus",
  "Maximiliano",
  "Miguel Ángel",
  "Noah",
  "Norberto",
  "Octavio",
  "Óscar",
  "Pablo",
  "Raúl",
  "Roberto",
  "Sancho",
  "Sergi",
  "Sergio",
  "Théo",
  "Tomás",
  "Vicente"
] as const;

export const femaleFirstNames = [
  "Adela",
  "Amalia",
  "Ana Júlia",
  "Ana Laura",
  "Antonia",
  "Beatriz",
  "Berta",
  "Carmen",
  "Catalina",
  "Cecília",
  "Clara",
  "Concepción",
  "Dulce María",
  "Eva",
  "Felícia",
  "Florencia",
  "Giovanna",
  "Helena",
  "Heloísa",
  "Inés",
  "Isabelly",
  "Jazmin",
  "Jimena",
  "Karla",
  "Laura",
  "Lilia",
  "Liz",
  "Lucia",
  "Lucía",
  "Manuela",
  "Marcela",
  "Margarida",
  "Maria Eduarda",
  "María Eugenia",
  "Maria Júlia",
  "María Luisa",
  "María Teresa",
  "Mariana",
  "Marilu",
  "Marilú",
  "Melissa",
  "Micaela",
  "Monserrat",
  "Natalia",
  "Nicole",
  "Norma",
  "Núbia",
  "Paula",
  "Rafaela",
  "Rebeca",
  "Rosa María",
  "Rosalia",
  "Rosario",
  "Sofía",
  "Soledad",
  "Sonia",
  "Talita",
  "Teresa",
  "Verónica",
  "Yamileth"
] as const;

export const maleLastNames = [
  "Abreu Coronado",
  "Adame Baeza",
  "Alanis Reyna",
  "Anaya Saldaña",
  "Barrios Ozuna",
  "Batista",
  "Caraballo Figueroa",
  "Cardona Barragán",
  "Carvalho",
  "Franco",
  "Garibay Téllez",
  "Granados Vallejo",
  "Lucero Loera",
  "Macedo",
  "Martins",
  "Maya Colunga",
  "Meléndez Hurtado",
  "Mireles Marrero",
  "Moraes",
  "Moya Borrego",
  "Muñiz Ávalos",
  "Nazario Acuña",
  "Nogueira",
  "Parra Alba",
  "Reis",
  "Reséndez Armendáriz",
  "Ruiz Cortés",
  "Santos",
  "Saraiva",
  "Sisneros de Karen",
  "Souza",
  "Téllez Matías",
  "Tirado Alaníz",
  "Tórrez de Frías",
  "Valencia Chávez",
  "Valentín Vaca",
  "Vargas Corrales",
  "Vega Dávila",
  "Véliz Quesada",
  "Zavala Benítez"
] as const;

export const femaleLastNames = [
  "Amador Centeno",
  "Arteaga Ávalos",
  "Báez Ramón",
  "Barros",
  "Batista",
  "Blanco Loera",
  "Cadena Maestas",
  "Camarillo Kyra",
  "Carvalho",
  "Concepción Armenta",
  "Cornejo Arce",
  "Cortés Tejeda",
  "Garibay Valadez",
  "Gil Rivera",
  "Guajardo de Sandoval",
  "Jimínez Acuña",
  "Macedo",
  "Mascareñas Duarte",
  "Melo",
  "Miranda Munguía",
  "Montemayor Botello",
  "Montemayor Figueroa",
  "Montero Godínez",
  "Moreira",
  "Moreno Quezada",
  "Murillo Linares",
  "Navarro Venegas",
  "Oliveira",
  "Ornelas Huixtlacatl",
  "Quevedo Saiz",
  "Reis",
  "Santos",
  "Serrano Montaño",
  "Silva",
  "Tirado Arenas",
  "Tovar de Gamez",
  "Valladares Karam",
  "Yami Barela",
  "Yami Tórrez",
  "Zepeda Osorio"
] as const;
