export const maleFirstNames = [
  "Agustín",
  "Alexander",
  "Alfonso",
  "Andrés",
  "Ángel Daniel",
  "Axel",
  "Benito",
  "Benjamín",
  "Bryan",
  "Carlos",
  "César",
  "Claudio",
  "Davi",
  "Diego",
  "Gonzalo",
  "Gregorio",
  "Heitor",
  "Hélio",
  "Henrique",
  "Hernán",
  "Hugo",
  "Ignacio",
  "Isaac",
  "Israel",
  "João Lucas",
  "Joaquim",
  "Jorge",
  "Jorge Luis",
  "José",
  "José Luis",
  "José Miguel",
  "Josep",
  "Juan Carlos",
  "Kevin",
  "Lucas",
  "Lucca",
  "Luis",
  "Luis Fernando",
  "Manuel",
  "Marcelo",
  "Miguel",
  "Noah",
  "Óscar",
  "Pablo",
  "Pío",
  "Ramiro",
  "Ramón",
  "Raúl",
  "Roberto",
  "Salvador",
  "Samuel",
  "Sergi",
  "Sergio",
  "Tadeo",
  "Teodoro",
  "Tertuliano",
  "Théo",
  "Tomás",
  "Vicente",
  "Víctor"
] as const;

export const femaleFirstNames = [
  "Adriana",
  "Alessandra",
  "Alice",
  "Ana Clara",
  "Ana Victoria",
  "Barbara",
  "Berta",
  "Bruna",
  "Carla",
  "Clara",
  "Claudia",
  "Diana",
  "Dorotea",
  "Eloá",
  "Elsa",
  "Elvira",
  "Estefanía",
  "Estela",
  "Ester",
  "Esther",
  "Eva",
  "Guillermina",
  "Helena",
  "Irene",
  "Isabel",
  "Isabelly",
  "Laura",
  "Lavínia",
  "Leticia",
  "Lourdes",
  "Lucía",
  "Luisa",
  "Manuela",
  "Marcela",
  "Maria",
  "María de Jesús",
  "María del Carmen",
  "Maria Helena",
  "Mariana",
  "Maricarmen",
  "Marina",
  "Marisol",
  "Marli",
  "Matilde",
  "Melany",
  "Melissa",
  "Mercedes",
  "Miranda",
  "Natália",
  "Norma",
  "Pilar",
  "Rafaela",
  "Ramona",
  "Renata",
  "Rocio",
  "Sara",
  "Verónica",
  "Virginia",
  "Yamileth",
  "Yasmin"
] as const;

export const maleLastNames = [
  "Ballesteros Godínez",
  "Barreto Castellanos",
  "Braga",
  "Concepción de Serrano",
  "Cornejo Montenegro",
  "Costa",
  "Durán Alicea",
  "Echevarría Raya",
  "Flores Márquez",
  "Gálvez Escamilla",
  "Gil Casares",
  "Holguín Alonzo",
  "Khalid Villareal",
  "Linares Korta",
  "Lomeli Delapaz",
  "Macías Lara",
  "Melo",
  "Montemayor Cortés",
  "Moraes",
  "Moreira",
  "Muñoz Kardache soto",
  "Nieto Aguirre",
  "Ortega Abeyta",
  "Osorio Krauel natera",
  "Padilla Colón",
  "Padrón Quintanilla",
  "Patiño Covarrubias",
  "Pulido Terrazas",
  "Ramírez Garica",
  "Rentería Correa",
  "Rodríquez Alba",
  "Saraiva",
  "Serna Muñoz",
  "Souza",
  "Suárez Collazo",
  "Terrazas Gutiérrez",
  "Urrutia Galarza",
  "Velázquez Casas",
  "Xavier",
  "Zapata Navarrete"
] as const;

export const femaleLastNames = [
  "Acevedo Rosario",
  "Alemán Villanueva",
  "Arroyo Palacios",
  "Braga",
  "Bueno Aparicio",
  "Carvalho",
  "Castellanos Ayala",
  "Cavazos Ozuna",
  "Cepeda Borrego",
  "Curiel Hurtado",
  "Escobar Cruz",
  "Franco",
  "Garza Ávila",
  "Guardado Tirado",
  "Koenig Adame",
  "Krauel natera Abrego",
  "Madrid Bernal",
  "Mayorga de Esquibel",
  "Medrano Valdivia",
  "Melo",
  "Menchaca Saavedra",
  "Moya Alejandro",
  "Murillo Carmona",
  "Narváez Candelaria",
  "Nogueira",
  "Oliveira",
  "Palomino Vaca",
  "Pereira",
  "Reis",
  "Romo Kortajarena",
  "Santana de Vanegas",
  "Santillán Mateo",
  "Santos",
  "Saraiva",
  "Tamez Valdivia",
  "Verduzco Rodarte",
  "Villagómez Montéz",
  "Xavier",
  "Zambrano Palomo",
  "Zapata Godínez"
] as const;
