export const maleFirstNames = [
  "Agustín",
  "Alfonso",
  "Arturo",
  "Benito",
  "Bernardo",
  "Brayan",
  "Calebe",
  "Carlos",
  "César",
  "Cristián",
  "Cristobal",
  "Deneval",
  "Eduardo",
  "Emiliano",
  "Enrique",
  "Enzo Gabriel",
  "Ernesto",
  "Fabiano",
  "Fabrício",
  "Fernando",
  "Fernando Javier",
  "Francisco",
  "Gerardo",
  "Hernán",
  "Homero",
  "Hugo",
  "Ígor",
  "Isaac",
  "João",
  "João Pedro",
  "Joaquim",
  "Jorge Luis",
  "José Eduardo",
  "José María",
  "Julio César",
  "Lorenzo",
  "Lucca",
  "Manuel",
  "Marco Antonio",
  "Mario",
  "Mateo",
  "Miguel",
  "Murilo",
  "Nicolas",
  "Octavio",
  "Pedro",
  "Pietro",
  "Ramón",
  "Ricardo",
  "Roberto",
  "Rubén",
  "Salvador",
  "Samuel",
  "Santiago",
  "Sirineu",
  "Timoteo",
  "Tomás",
  "Vitor",
  "Washington",
  "Yuri"
] as const;

export const femaleFirstNames = [
  "Abril",
  "Adriana",
  "Amalia",
  "Ana Laura",
  "Ana María",
  "Ana Victoria",
  "Antonia",
  "Beatriz",
  "Carolina",
  "Célia",
  "Clara",
  "Cristina",
  "Dalila",
  "Elena",
  "Elisa",
  "Elizabeth",
  "Elsa",
  "Esperanza",
  "Estefanía",
  "Florencia",
  "Giovanna",
  "Guadalupe",
  "Isabel",
  "Ivanna",
  "Joana",
  "Laura",
  "Liz",
  "Lourdes",
  "Lucía",
  "Luisa",
  "Luz",
  "Maitê",
  "Margarita",
  "María",
  "Maria Alice",
  "María Cristina",
  "Maria Eduarda",
  "Mariana",
  "Maricarmen",
  "Marilu",
  "Marilú",
  "Marta",
  "Mércia",
  "Núbia",
  "Paula",
  "Rebeca",
  "Reina",
  "Rocio",
  "Rosa María",
  "Sara",
  "Sarah",
  "Sofía",
  "Sonia",
  "Talita",
  "Verónica",
  "Victoria",
  "Virginia",
  "Ximena Guadalupe",
  "Xochitl",
  "Yasmin"
] as const;

export const maleLastNames = [
  "Adorno Campos",
  "Alaníz Vaca",
  "Albuquerque",
  "Almonte Robledo",
  "Batista Ruiz",
  "Braga",
  "Corral Madrid",
  "Cotto Meza",
  "Dávila Beltrán",
  "Estévez Muñiz",
  "Gamboa Zúñiga",
  "Guerra Navarrete",
  "Gurule de Cintrón",
  "Kara Córdova",
  "Limón Sierra",
  "Macedo",
  "Mares Núñez",
  "Melo",
  "Nazario Corrales",
  "Nogueira",
  "Ochoa Negrete",
  "Oliveira",
  "Olmos Menchaca",
  "Olvera Muñiz",
  "Pantoja Saucedo",
  "Pereira",
  "Peres Loera",
  "Quintanilla Munguía",
  "Reis",
  "Roybal Serna",
  "Rubio Villareal",
  "Salcido Miramontes",
  "Santos",
  "Saraiva",
  "Sisneros Arce",
  "Solorzano Zambrano",
  "Sosa Covarrubias",
  "Torres Niño",
  "Valentín de Benavídez",
  "Xavier"
] as const;

export const femaleLastNames = [
  "Abeyta Pizarro",
  "Arredondo Trejo",
  "Ávila Barajas",
  "Badillo Sauceda",
  "Báez Carrera",
  "Braga",
  "Carreón Valdivia",
  "Cazares Canales",
  "Cortés Arenas",
  "Costa",
  "Delgado Naranjo",
  "Delrío Verdugo",
  "Echevarría Arreola",
  "Flórez Cardona",
  "Gámez Juárez",
  "Gaona Quintanilla",
  "Jaime Peralta",
  "Jaramillo Flórez",
  "Kanimal Delacrúz",
  "Luna Carrera",
  "Macedo",
  "Márquez Gómez",
  "Medina Farías",
  "Melo",
  "Miranda de Xairo Belmonte",
  "Mondragón Magaña",
  "Moraes",
  "Nogueira",
  "Oliveira",
  "Pelayo Olivera",
  "Pereira",
  "Portillo Tijerina",
  "Santos",
  "Saraiva",
  "Sosa Olivares",
  "Souza",
  "Tórrez Concepción",
  "Ureña Quiñónez",
  "Vargas Vaca",
  "Verdugo Madrigal"
] as const;
