export const maleFirstNames = [
  "Abraham",
  "Agustín",
  "Alberto",
  "Alexis",
  "Alfredo",
  "Antônio",
  "Bernardo",
  "Brandon",
  "Calebe",
  "Carlos",
  "Claudio",
  "Davi",
  "Eduardo",
  "Elías",
  "Elísio",
  "Emanuel",
  "Emilio",
  "Fabiano",
  "Fábio",
  "Fernando",
  "Frederico",
  "Gabriel",
  "Gilberto",
  "Gúbio",
  "Gustavo",
  "Heitor",
  "Hugo",
  "Ignacio",
  "Isaac",
  "Javier",
  "João",
  "João Pedro",
  "Jordi",
  "Jorge",
  "José",
  "José Antonio",
  "Jose Daniel",
  "José Emilio",
  "José Miguel",
  "Josep",
  "Juan",
  "Juan Carlos",
  "Julio",
  "Júlio",
  "Kléber",
  "Lorenzo",
  "Luis Ángel",
  "Luis Miguel",
  "Marcos",
  "Maximiliano",
  "Miguel Ángel",
  "Nicolás",
  "Octavio",
  "Pablo",
  "Paulo",
  "Ramiro",
  "Samuel",
  "Sancho",
  "Santiago",
  "Vicente"
] as const;

export const femaleFirstNames = [
  "Ana",
  "Ana Clara",
  "Ana Júlia",
  "Ana María",
  "Ana Victoria",
  "Anni",
  "Antonella",
  "Barbara",
  "Beatriz",
  "Berta",
  "Blanca",
  "Caridad",
  "Carmen",
  "Cecília",
  "Concepción",
  "Dalila",
  "Diana",
  "Eduarda",
  "Elena",
  "Elisa",
  "Eloisa",
  "Elsa",
  "Emily",
  "Esperanza",
  "Estela",
  "Felícia",
  "Gabriela",
  "Giovanna",
  "Guadalupe",
  "Inés",
  "Isabella",
  "Isis",
  "Jennifer",
  "Lara",
  "Leonor",
  "Magdalena",
  "Maitê",
  "Manuela",
  "Marcela",
  "Maria",
  "Maria Cecília",
  "Maria Clara",
  "María Cristina",
  "María Eugenia",
  "María Fernanda",
  "Maria Helena",
  "Maria Júlia",
  "Mariana",
  "Meire",
  "Mercedes",
  "Mércia",
  "Micaela",
  "Rosa María",
  "Sara",
  "Suélen",
  "Valentina",
  "Victoria",
  "Virginia",
  "Ximena Guadalupe",
  "Yaretzi"
] as const;

export const maleLastNames = [
  "Alaniz Carrera",
  "Albuquerque",
  "Arias Feliciano",
  "Barrera Sanabria",
  "Barros",
  "Bonilla Alarcón",
  "Fernández Murillo",
  "Franco",
  "Franco Rubio",
  "Galindo Quiñónez",
  "García Rosas",
  "González Díaz",
  "Guerra Olivera",
  "Herrera Cazares",
  "Hurtado Leiva",
  "Macedo",
  "Marín Banda",
  "Martins",
  "Moreira",
  "Oquendo Kamal",
  "Palacios Guerra",
  "Prieto Avilés",
  "Puente Ulloa",
  "Quintanilla Verdugo",
  "Reis",
  "Rendón de Zúñiga",
  "Robles Casas",
  "Robles Pacheco",
  "Rosario Ávila",
  "Roybal Vergara",
  "Saldivar Collado",
  "Saraiva",
  "Sevilla Pizarro",
  "Silva",
  "Tamayo Villegas",
  "Téllez Adame",
  "Tijerina Villalpando",
  "Tórrez Hernandes",
  "Valles Velázquez",
  "Zamudio Delao"
] as const;

export const femaleLastNames = [
  "Adorno Valle",
  "Alva Covarrubias",
  "Araña Nava",
  "Armenta Godoy",
  "Barraza Raya",
  "Barros",
  "Berríos Adorno",
  "Braga",
  "Brito Carvajal",
  "Carvalho",
  "Cepeda Peralta",
  "Contreras López",
  "Córdova Puente",
  "Correa Ramos",
  "Domínquez Sepúlveda",
  "Franco",
  "Galarza Brito",
  "Girón Méndez",
  "Jaime Correa",
  "Lira Rangel",
  "Martins",
  "Molina Madera",
  "Morales Romero",
  "Ñañez Zarate",
  "Nevárez Bernal",
  "Oliveira",
  "Olmos Valle",
  "Ortega Guardado",
  "Prado Alanis",
  "Reis",
  "Robledo Anguiano",
  "Saraiva",
  "Serna Meza",
  "Silva",
  "Souza",
  "Valladares Cintrón",
  "Xavier",
  "Ybarra Crespo",
  "Zamora Muro",
  "Zepeda Robledo"
] as const;
