export const maleFirstNames = [
  "Adán",
  "Alejandro",
  "Alfonso",
  "Alfredo",
  "Ángel Gabriel",
  "Antonio",
  "Autumn",
  "Barry",
  "Bernardo",
  "Carles",
  "Conrad",
  "Cristobal",
  "Cristóbal",
  "Dexter",
  "Drake",
  "Emilio",
  "Enrique",
  "Ernesto",
  "Francisco",
  "Franklin",
  "Germán",
  "Gilbert",
  "Gonzalo",
  "Gustavo",
  "Hermenegildo",
  "Hernán",
  "Hugo",
  "Ignacio",
  "Jalon",
  "Jaunita",
  "Javier",
  "Jeremiah",
  "Jerónimo",
  "Jolie",
  "José Luis",
  "José María",
  "Juan",
  "Julio",
  "Julio César",
  "Kristoffer",
  "Kyra",
  "Leonie",
  "Lionel",
  "Luis Miguel",
  "Mateo",
  "Miguel",
  "Miguel Ángel",
  "Pablo",
  "Patricio",
  "Ramón",
  "Rubén",
  "Ryann",
  "Samuel",
  "Stewart",
  "Tristian",
  "Vicente",
  "Víctor",
  "Wade",
  "Wesley",
  "Zachary"
] as const;

export const femaleFirstNames = [
  "Ada",
  "Alejandra",
  "Alexandra",
  "Amelia",
  "Amparo",
  "Ana",
  "Ángela",
  "Antonia",
  "Araceli",
  "Ariadna",
  "Camila",
  "Catalina",
  "Cecilia",
  "Concepción",
  "Darwin",
  "Débora",
  "Dimitri",
  "Dora",
  "Elena",
  "Eloisa",
  "Eunice",
  "Florence",
  "Florencia",
  "Frances",
  "Gabriela",
  "Giles",
  "Guadalupe",
  "Isabel",
  "Isabela",
  "Joy",
  "Juana",
  "Kathleen",
  "Kimberly",
  "Laura",
  "Lilia",
  "Lindsey",
  "Lorena",
  "Lourdes",
  "Luz",
  "María Eugenia",
  "María Luisa",
  "Marilu",
  "Marisol",
  "Marjorie",
  "Mónica",
  "Nicole",
  "Noemi",
  "Retta",
  "Rocío",
  "Silvia",
  "Soledad",
  "Sonia",
  "Susana",
  "Tatyana",
  "Terri",
  "Tyrel",
  "Valeria",
  "Verna",
  "Verónica",
  "Zoe"
] as const;

export const maleLastNames = [
  "Abeyta Ballesteros",
  "Buckridge",
  "Collazo Padrón",
  "Cruz Alcántar",
  "Gaitán de Urbina",
  "Galindo Vázquez",
  "Graham",
  "Guardado Velázquez",
  "Jáquez Quezada",
  "Koss",
  "Ledesma Calderón",
  "Leiva Velázquez",
  "Lockman",
  "Luna Quezada",
  "Macías Gómez",
  "Mante",
  "Marín Henríquez",
  "Mateo Barragán",
  "Miramontes Barreto",
  "Pedroza Hurtado",
  "Price",
  "Quevedo Alvarado",
  "Quiñónez de Varela",
  "Quiróz Abeyta",
  "Rendón Ortiz",
  "Rice",
  "Rodarte Marroquín",
  "Rowe",
  "Ruecker",
  "Russel",
  "Schamberger",
  "Stokes",
  "Tillman",
  "Trejo de Becerra",
  "Vaca Yanes",
  "Valdez Osorio",
  "Vanegas Ibarra",
  "Villa Treviño",
  "Zapata Estrada",
  "Zavala Villarreal"
] as const;

export const femaleLastNames = [
  "Aguilar Sisneros",
  "Alfaro Contreras",
  "Archuleta Ozuna",
  "Botsford",
  "Brown-Hintz",
  "Davis",
  "Figueroa Llamas",
  "Hagenes-Senger",
  "Hettinger-Bode",
  "Jacobi",
  "Jenkins",
  "Lemus Castañeda",
  "Longoria Montenegro",
  "Lowe",
  "Luna Saldaña",
  "Merino Vallejo",
  "Mondragón Holguín",
  "Montañez Hernandes",
  "Moreno Mondragón",
  "Mota Guzmán",
  "Mraz",
  "O'Kon",
  "Olivo Rivas",
  "Pantoja de Xiana",
  "Rath",
  "Raya Concepción",
  "Riojas Paz",
  "Robledo Ybarra",
  "Rojo Mireles",
  "Rowe",
  "Saldivar Escobedo",
  "Sanches Armijo",
  "Sisneros Vanegas",
  "Soliz Córdova",
  "Tello Gallardo",
  "Valdés Saldaña",
  "Valladares Navarrete",
  "Villanueva Angulo",
  "Windler",
  "Xiana Garica"
] as const;
