export const maleFirstNames = [
  "Adán",
  "Alfonso",
  "Alfredo",
  "Antonio",
  "Aubree",
  "Camron",
  "Carles",
  "Casimir",
  "César",
  "Cristobal",
  "David",
  "Devin",
  "Elías",
  "Eliseo",
  "Emilio",
  "Esteban",
  "Garry",
  "Homero",
  "Hugo",
  "Iker",
  "Irving",
  "Ivan",
  "Jesús",
  "Joaquín",
  "Jorge",
  "José Antonio",
  "Julian",
  "Julio",
  "Julio César",
  "Kenneth",
  "Kirk",
  "Lacy",
  "Lorenzo",
  "Louisa",
  "Maida",
  "Marcos",
  "Mariano",
  "Martín",
  "Mateo",
  "Neil",
  "Ova",
  "Pío",
  "Rafael",
  "Ramón",
  "Reggie",
  "Robbie",
  "Roman",
  "Rubén",
  "Salvador",
  "Sammy",
  "Santiago",
  "Timoteo",
  "Tomás",
  "Toney",
  "Vicente",
  "Víctor",
  "Victor Manuel",
  "Vivienne",
  "Walter",
  "Winona"
] as const;

export const femaleFirstNames = [
  "Alexa",
  "Alysson",
  "Ana Luisa",
  "Ana María",
  "Anita",
  "Berta",
  "Carla",
  "Carolina",
  "Catalina",
  "Cornell",
  "Darlene",
  "Débora",
  "Dell",
  "Elena",
  "Elisa",
  "Ellen",
  "Eloisa",
  "Erwin",
  "Gabriela",
  "Gaston",
  "Gloria",
  "Guadalupe",
  "Guillermina",
  "Haleigh",
  "Harriet",
  "Inés",
  "Isobel",
  "Ivanna",
  "Josefina",
  "Karla",
  "Katherine",
  "Kimberly",
  "Kristina",
  "Leticia",
  "Liliana",
  "Manuela",
  "Marguerite",
  "María Cristina",
  "María de los Ángeles",
  "María Luisa",
  "Mariana",
  "Marisol",
  "Marquise",
  "Mayte",
  "Mercedes",
  "Micaela",
  "Millie",
  "Norma",
  "Olive",
  "Ramona",
  "Rebeca",
  "Renata",
  "Rosa",
  "Rosalia",
  "Roser",
  "Sofia",
  "Sonia",
  "Sonya",
  "Virginia",
  "Zita"
] as const;

export const maleLastNames = [
  "Arguello Zarate",
  "Balderas Salazar",
  "Casárez Valdez",
  "Conn",
  "Cremin",
  "de Anda Montemayor",
  "Escobedo Matos",
  "Fernández Vázquez",
  "Granados Salcido",
  "Haro Alonzo",
  "Karem de Carmona",
  "Karem Vásquez",
  "Koch",
  "Lindgren",
  "Lubowitz",
  "McClure",
  "Mercado Trejo",
  "Montez Salgado",
  "Morissette",
  "Oquendo Arteaga",
  "Peres Bétancourt",
  "Price",
  "Reinger",
  "Rodríguez Velázquez",
  "Rohan",
  "Rowe",
  "Saldivar Páez",
  "Sedillo Rodrígez",
  "Simonis",
  "Sisneros Terán",
  "Soto Guzmán",
  "Toro Bañuelos",
  "Trantow",
  "Valadez Zamarreno",
  "Vallejo Pizarro",
  "Vanegas Vallejo",
  "Vargas Armas",
  "Vázquez Zamarreno",
  "Venegas Fajardo",
  "Zambrano de Cuellar"
] as const;

export const femaleLastNames = [
  "Arellano Ávila",
  "Bañuelos Sánchez",
  "Bradtke",
  "Bravo Hurtado",
  "Carrion Iglesias",
  "Castro de Hernández",
  "Cintrón Casas",
  "Cole",
  "Cornejo de Carrion",
  "Duarte Quesada",
  "Espino Barragán",
  "Fuentes Serrano",
  "Guerrero Corrales",
  "Hand",
  "Hickle",
  "Hurtado Curiel",
  "Juárez Solorio",
  "Kunze",
  "Laureano Ceballos",
  "León Cadena",
  "Mata Adorno",
  "Mata Lucio",
  "Mills",
  "Monroy Ordóñez",
  "Morar-Wintheiser",
  "Mueller",
  "Ocampo Llamas",
  "Ortiz",
  "Padrón Zúñiga",
  "Palomino Monroy",
  "Pizarro Duarte",
  "Rangel Trujillo",
  "Reichert",
  "Reilly",
  "Rico Menéndez",
  "Ríos Serrato",
  "Rubio Monroy",
  "Salgado Escobedo",
  "Schneider",
  "Solís Briseño"
] as const;
